spring: 
  redis:
    host: 10.0.0.230  
    port: 6379    
    password: crs-4wny33j2:Ut%3f2#dfg
    timeout: 60000
    database: 15
    jedis:
      pool:
        max-active: -1     # 连接池最大连接数（使用负值表示没有限制）
        max-wait:   -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle:   8      # 连接池中的最大空闲连接
        min-idle:   0      # 连接池中的最小空闲连接
        max-total:  10000
        holed: 2000