spring: 
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.vendor.MySqlExceptionSorter
      url: jdbc:mysql://localhost:3306/mysql
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
